Project I.G.I. (released in North America as Project I.G.I.: I'm Going In) is a tactical first-person shooter video game developed by Innerloop Studios and released on December 15, 2000 by Eidos Interactive. Upon release the game received mixed reviews due to a number of shortcomings, including poorly programmed A.I., lack of a mid-game save option, and the lack of multiplayer features. However it was praised for its superb sound design and graphics, thanks in part to its use of a proprietary game engine that was previously used in Innerloop's Joint Strike Fighter.
It was followed up in 2003 by I.G.I.-2: Covert Strike.


== Plot ==
The protagonist Jones, with the help of Anya, infiltrates the base of Josef Priboi in order to capture him and extract the knowledge of the stolen Warhead. While Josef Priboi is taken away in a helicopter by Jones, the copter is shot down by Ekk. The Russians take Priboi, as well as Jones' equipment. Jones then has to clear the border and find his equipment. He then hijacks the train carrying Priboi and takes him in for interrogation. Learning about the involvement of Ekk, he sets off to catch her and find the nuclear weapon. Ekk escapes on her first meeting with Jones, but Jones kills her after finding her second hideout as well.


== Reception ==
Project I.G.I. received a "Silver" sales award from the Entertainment and Leisure Software Publishers Association (ELSPA), indicating sales of at least 100,000 copies in the United Kingdom.


== References ==


== External links ==
Project I.G.I.' at MobyGames
Project I.G.I. on IMDb